import type { AnalysisResponse } from "../../../types/analysis";
import { CoachRecommendation } from "./CoachRecommendation";
import { FactorsList } from "./FactorsList";
import { FormationsSection } from "./FormationsSection";
import { GameFlow } from "./GameFlow";
import { KeyBattles } from "./KeyBattles";
import { MatchHeader } from "./MatchHeader";
import { ScoreBar } from "./ScoreBar";
import { TacticalInsights } from "./TacticalInsights";
import { TeamPanel } from "./TeamPanel";

interface MatchAnalysisResultsProps {
  analysis: AnalysisResponse;
  model: string;
}

export function MatchAnalysisResults({
  analysis,
  model,
}: MatchAnalysisResultsProps) {
  const homeName = analysis.homeTeam.name;
  const awayName = analysis.awayTeam.name;

  return (
    <article className="flex flex-col gap-6">
      <MatchHeader analysis={analysis} />

      <section
        aria-label="Team profiles"
        className="grid gap-4 sm:grid-cols-2"
      >
        <TeamPanel team={analysis.homeTeam} side="home" />
        <TeamPanel team={analysis.awayTeam} side="away" />
      </section>

      <FormationsSection
        matchup={analysis.formations}
        homeName={homeName}
        awayName={awayName}
      />

      <section
        aria-label="Team ratings"
        className="grid gap-3 sm:grid-cols-2"
      >
        <ScoreBar
          label="Pressing intensity"
          homeValue={analysis.pressingScore.home}
          awayValue={analysis.pressingScore.away}
          homeName={homeName}
          awayName={awayName}
        />
        <ScoreBar
          label="Possession profile"
          homeValue={analysis.possessionScore.home}
          awayValue={analysis.possessionScore.away}
          homeName={homeName}
          awayName={awayName}
        />
        <ScoreBar
          label="Attacking threat"
          homeValue={analysis.attackingThreat.home}
          awayValue={analysis.attackingThreat.away}
          homeName={homeName}
          awayName={awayName}
        />
        <ScoreBar
          label="Defensive stability"
          homeValue={analysis.defensiveStability.home}
          awayValue={analysis.defensiveStability.away}
          homeName={homeName}
          awayName={awayName}
        />
      </section>

      <div className="grid gap-4 lg:grid-cols-2">
        <FactorsList
          title="Strengths"
          homeName={homeName}
          awayName={awayName}
          homeItems={analysis.strengths.home}
          awayItems={analysis.strengths.away}
        />
        <FactorsList
          title="Weaknesses"
          homeName={homeName}
          awayName={awayName}
          homeItems={analysis.weaknesses.home}
          awayItems={analysis.weaknesses.away}
        />
      </div>

      <KeyBattles
        homeName={homeName}
        awayName={awayName}
        battles={analysis.keyBattles}
      />

      <TacticalInsights insights={analysis.tacticalInsights} />

      <GameFlow flow={analysis.expectedGameFlow} />

      <CoachRecommendation
        homeName={homeName}
        awayName={awayName}
        recommendation={analysis.coachRecommendation}
      />

      <p className="text-right text-xs text-white/35">
        Generated by {model}
      </p>
    </article>
  );
}